### ISSUE TITLE
Add a License to Project

### ISSUE THREAD

**Issue by 0xhanif** [0xhanif/github-projects-playground#3]
Hey @Fadhilat606 . I wonder what type of license I should add to this project.

**Comment by Fadhilat606** [comment]
We usually use MIT license. I think that will be perfect for this project.

**Comment by 0xhanif** [comment]
Thank @Fadhilat606 , you're the best. I added the LICENSE file.

**Comment by 0xhanif** [comment]
Thank @Fadhilat606  , you're the best. I added the LICENSE file.
